### ISSUE TITLE
add a way to apply an object's fields as top-level API arguments.

### ISSUE THREAD

**Issue by toumorokoshi** [toumorokoshi/transmute-core#8]
It's common in rest APIs to just put the object as the top-level argument. this isn't possible in transmute right now: the best you can get is a single top level key corresponding to the richer object.

there should be some way to lay out an object as the api arguments instead.

**Comment by toumorokoshi** [comment]
I was thinking additional descriptors that handle mapping of explicit parameter types:

```
class MyBody(Model):
    name = StringType()

# this declares a mapping of the body to the "body" parameter. 
@body("body", MyBody)
def my_route(body):
     assert body.name == "myname"
```
Theoretically, this could also be applied to get/header/path parameters as well.

**Comment by rvangraan** [comment]
There seems to be two different mapping models, one where the parameters of the function are mapped to request/body parameters (the current scenario) and the one in this issue where you don't want the content of the body interpreted, but just passed straight through. As I showed in my request, I think it is natural to name the parameter of the function `body` as you and I both did. But to keep it consistent with the current behaviour, I'd rather not have the body type like this `@body("body", MyBody)` simply because you would then have an ambiguity if you do this:
```
@body("body", MyBody)
def my_route(body: str):
     assert body.name == "myname"
```

So why not just this:

```
@body("body")
def my_route(body: MyBody):
  ...
```
This declares that the body of the request should be called `body`. Then it will be possible to have requests with a parameter named `"body"` as well, or name the body any way you want:

```
    @aiohttp_transmute.describe(
        methods='GET',
        path_parameters=['my_id'],
        body="request_body"
        response_types={
            200: {
                'description': 'Found',
                'type': Body
            }
        }
    )
def my_route(my_id, request_body: MyBody):
  ...
```
Also, `body` and `body_parameters` should be mutually exclusive.

**Comment by toumorokoshi** [comment]
The addition to describe make a lot of sense. I was thinking about the body/body_parameter issue, and it is possible to change behavior based on whether the argument is a string or a list:

`body_parameters='request_body` would result in the whole body serialized into that document

`body_parameters=['foo', 'bar']` would result in spreading the body and converting into multiple arguments.

thoughts? I'm working on some changes to enable this on the backend side, in a 2.0 branch.

**Comment by toumorokoshi** [comment]
This now exists in 1.3.0, as a string into body_parameters.

http://transmute-core.readthedocs.io/en/latest/function.html#use-a-single-schema-for-the-body-parameter.
